version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/project2
    overwrite: yes

file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu
    pattern: '**'
    owner: sudo
    group: sudo

hooks:
  AfterInstall:
    - location: scripts/after-deploy.sh
      timeout: 300
      runas: sudo
      # runas는 사용자 이름