export enum ERecipeCategory {
    coffee_mlik = "커피우유",
    whipping_cream = "휘핑크림",
    vanilla_syrup = "바닐라 시럽",
    hazelnut_syrup = "헤이즐넛 시럽",

    cramel_syrup = "카라멜 시럽",
    choco_green_tea = "초코 녹차",
    tea = "홍차",
    strawberry = "딸기",
    green_grape = "청포도",
    orange = "오렌지",
    grapefruit = "자몽",
    lemon = "레몬",
    blue_berry = "블루베리",
    tapioca_pearl = "타피오카 펄",
    sparkling_water = "탄산수",
    mint = "민트",
    cinnamon = "시나몬",
}
