name: Automated-Deploy

on:
  push:
    branches:
      - 'main'

#  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Zip file
        run: zip -r ${{github.event.pull_request.timestamp}}_server.zip .github/workflows ./scripts ./jest ./src ./test ./appspec.yml ./gitignore ./package.json ./package-lock.json ./tsconfig.build.json ./tsconfig.json ./jest.config.json

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CUPICK_S3_CODEDEPLOY_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_CUPICK_S3_CODEDEPLOY_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Automated Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./${{github.event.pull_request.timestamp}}_server.zip s3://cupick-s3-codedeploy
        # https://isntyet.tistory.com/126

      - name: Automated Deployment to EC2 with CodeDeploy
        run: aws deploy create-deployment
          --application-name cupick-codedeploy
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name cupick-server-codedeploy-group
          --s3-location bucket=cupick-s3-codedeploy,bundleType=zip,key=${{github.event.pull_request.timestamp}}_server.zip