
name: CI

on:
  push:
    branches: ['feature/cicd']
  pull_request:
    branches: ['main']

#  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # - name: Run a one-line script
      #   run: sudo -s

      # - name: create env
      #   run: |
      #     pwd
      #     touch .env
      #     echo DB_ID=${{ secrets.DB_ID }} >> .env
      #     echo DB_PW=${{ secrets.DB_PW }} >> .env
      #     echo DB_HOST=${{ secrets.DB_HOST }} >> .env
      #     echo DB=${{ secrets.DB }} >> .env
      #     echo GIT_ID=${{ secrets.GIT_ID }} >> .env
      #     echo GIT_SECRET=${{ secrets.GIT_SECRET }} >> .env
      #     echo GIT_URL=${{ secrets.GIT_URL }} >> .env
      #     echo REDIS_HOST=${{ secrets.REDIS_HOST }} >> .env
      #     echo REDIS_PORT=${{ secrets.REDIS_PORT }} >> .env
      #     echo REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} >> .env
      #     echo COOKIE_SECRET=${{ secrets.COOKIE_SECRET }} >> .env
      #     echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env

      - name: zip file
        run: zip -r hous.zip .github/workflows ./package.json ./package-lock.json ./src ./appspec.yml ./scripts .gitignore

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CUPICK_S3_CODEDEPLOY_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_CUPICK_S3_CODEDEPLOY_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./hous.zip s3://cupick-s3-codedeploy

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name cupick-codedeploy
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name cupick-server-codedeploy-group
          --s3-location bucket=cupick-s3-codedeploy,bundleType=zip,key=hous.zip
#
# - name: pm2 start
#   run: sudo pm2 start app.js
# - name: Cache node modules
#   uses: actions/cache@v1
#   with:
#     path: node_modules
#     key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
#     restore-keys: |
#       ${{ runner.OS }}-build-
#       ${{ runner.OS }}-

# - name: build server files
#   working-directory: ./
#   run: |
#     npm install

# - name: Build
#   run: npm run build

# - name: Deploy
#   env:
#     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#   run: |
#     aws s3 cp \
#     --recursive \
#     --region ap-northeast-2 \
#     /home/runner/work/actions/actions s3://sd-build