name: CI

on:
  push:
    branches: 'feature/cicd'
  pull_request:
    branches: ['main']

#  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: create env
        run: |
          pwd
          touch .env
          echo DB_ID=${{ secrets.DB_ID }} >> .env



      - name: Zip file
        run: zip -r 1234q_cupick-server.zip .github/workflows ./src ./scripts ./appspec.yml ./gitignore ./package.json ./package-lock.json ./tsconfig.json .env

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CUPICK_S3_CODEDEPLOY_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_CUPICK_S3_CODEDEPLOY_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./1234q_cupick-server.zip s3://cupick-s3-codedeploy
        # https://isntyet.tistory.com/126

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name cupick-codedeploy
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name cupick-server-codedeploy-group
          --s3-location bucket=cupick-s3-codedeploy,bundleType=zip,key=1234q_cupick-server.zip