
name: CI

on:
  push:
    branches: 'feature/cicd'
  pull_request:
    branches: ['main']

#  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: Hello World4
        run: echo 

      - name: zip file
        run: zip -r ${{github.event.head_commit.timestamp}}_cupick-server.zip .github/workflows ./package.json ./node_modules ./package-lock.json ./src ./appspec.yml ./scripts .gitignore

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CUPICK_S3_CODEDEPLOY_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_CUPICK_S3_CODEDEPLOY_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./${{github.event.head_commit.timestamp}}_cupick-server.zip s3://cupick-s3-codedeploy
        # https://isntyet.tistory.com/126

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name cupick-codedeploy
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name cupick-server-codedeploy-group
          --s3-location bucket=cupick-s3-codedeploy,bundleType=zip,key=${{github.event.head_commit.timestamp}}_cupick-server.zip
#
# - name: pm2 start
#   run: sudo pm2 start app.js
# - name: Cache node modules
#   uses: actions/cache@v1
#   with:
#     path: node_modules
#     key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
#     restore-keys: |
#       ${{ runner.OS }}-build-
#       ${{ runner.OS }}-

# - name: build server files
#   working-directory: ./
#   run: |
#     npm install

# - name: Build
#   run: npm run build

# - name: Deploy
#   env:
#     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#   run: |
#     aws s3 cp \
#     --recursive \
#     --region ap-northeast-2 \
#     /home/runner/work/actions/actions s3://sd-build